services:
  api:
    # use 1 worker per service, scale api services instead of gunicorn workers!
    user: "1000:1000"
    build: .
    restart: unless-stopped
    ports:
      - 127.0.0.1:8000:8000
    links:
      - redis
    environment:
      REDIS_URL: redis://redis
      CACHE: 1
      FTM_STORE_URI: sqlite:////data/followthemoney.store
    volumes:
      - ${DATA_ROOT:-.}/followthemoney.store:/data/followthemoney.store

  redis:
    user: "1000:1000"
    image: redis
    restart: unless-stopped
