services:
  api:
    build: .
    command: "--workers 4"
    restart: unless-stopped
    ports:
      - 127.0.0.1:8000:8000
    links:
      - redis
    environment:
      FTMQ_API_CACHE_URI: redis://redis
      FTMQ_API_USE_CACHE: true

    volumes:
      - ${DATA_ROOT:-.}/nomenklatura.db:/data/nomenklatura.db
      - ${DATA_ROOT:-.}/tests/fixtures/catalog.json:/data/catalog.json

  redis:
    image: redis
    restart: unless-stopped
